services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Optional: sync local changes automatically
    
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
